apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nexus-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app: nexus